### ISSUE TITLE
How can I get MKR token for Kovan testnet

### ISSUE THREAD

**Issue by tungnnt** [makerdao/governance-portal-v2#97]
I start the front-end repo, but I can't find anywhere to get MKR to use the system ?

**Comment by b-pmcg** [comment]
There is a faucet, but it appears to be empty at the moment: https://kovan.etherscan.io/address/0x94598157fcf0715c3bc9b4a35450cce82ac57b20

Try asking in the maker chat dev channel, maybe someone can send you some.

https://chat.makerdao.com/channel/dev

**Comment by b-pmcg** [comment]
@tungnnt unfortunately we don't have any kovan MKR to provide you, hopefully you could find some out there. We will be deploying the governance portal to the Goerli testnet soon, so stock up on Goerli ETH :)
