### ISSUE TITLE
RFC: Code Module structure

### ISSUE THREAD

**Issue by rafinskipg** [makerdao/governance-portal-v2#98]
## Code reorganization proposal.

The idea behind this proposal is to have a structure of code that is organized by responsibilities. 

/modules folder would replace /lib folder. Inside each module we would have:
- hooks: for client side hooks
- components: components related to this module
- api: fetch calls using web3 or other fetching mechanisms
- context: in case context are needed
- store: in case store is needed

Each module folder should have it's own tests contained.

```
/modules
  /esmodule
     /hooks
        /useESModuleData.tsx
     /components
        /ComponentSomething.tsx
        /__tests__
            /ComponentSomething.spec.tsx
     /types
        /esmodule.d.ts
     /api
        /fetchESModuleData.ts
        /__tests__
            /fetchESModuleData.spec.ts
     /esmodule.constants.ts
  /app
     /components
        /Button.tsx
     /hooks
       /useInitApp.tsx
  /account
      /hooks
         /useConnectAccount.tsx
      /lib
          /__tests__
             /mergeAccount.spec.ts
         /mergeAccounts.ts
  /maker
     /api
        /fetchMKRBalance.ts
        /fetchMKRStacked.ts
        /fetchMKRVoting.ts
     /hooks
         /useMKRBalance.tsx
         /useMKRLockeed.tsx
...
/pages
   /esmodule.tsx
   /...



```

**Comment by adamgoth** [comment]
I like this pattern in general. It worked well in a large project I previously worked on. I think the challenge is breaking down the app into the right "modules" since we use various hooks, API calls, etc across the app.

**Comment by b-pmcg** [comment]
I'm actually all for restructuring the code structure. The existing architecture was created long ago and maybe iterated over enough times where it no longer makes sense. Plus none of us had input on that.

I haven't had time to contemplate your specific suggestion here @rafinskipg but maybe its something we could all have a conversation about during a planning meeting after the MVP release.

**Comment by b-pmcg** [comment]
I did a little more research on code structuring best practices for nextjs projects and found others recommending the modules approach. I like the idea behind it, one suggestion (from [here](https://dev.to/vadorequest/a-2021-guide-about-structuring-your-next-js-project-in-a-flexible-and-efficient-way-472)) would be to add a `common` directory for code that doesn't fit into a specific module, reducing a bit of the "thought complexity" surrounding module structure. That way we get to add code quickly when necessary, but retain the benefit of thoughtful organization of modules.

**Comment by b-pmcg** [comment]
Just brainstorming some potential modules:
- Transactions
- Accounts
- Polling voting
- Executive voting
- Delegations
- Analytics
- MKR balance (or voting weight?)
- Maker/Dai.js

It's hard not to think about it 1:1 with our pages, I'm not sure if that's best practice or not.
